-- Upgrade embeddings model from text-embedding-3-small to text-embedding-3-large
-- Uses dimensions=1536 (Matryoshka truncation) so column size stays the same.
-- Old embeddings are cleared since they came from a different model.

-- Clear existing embeddings (generated by the old small model)
UPDATE atomic_items SET embedding = NULL WHERE embedding IS NOT NULL;
