import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Use | RatingIQ",
  description: "RatingIQ Terms of Use — Effective June 07, 2026",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen px-4 py-16" style={{ background: "var(--page-gradient)" }}>
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="inline-block mb-8">
          <img src="/logo.svg" alt="RatingIQ" style={{ height: "36px", width: "auto" }} className="logo-light" />
          <img src="/logo-white.svg" alt="RatingIQ" style={{ height: "36px", width: "auto" }} className="logo-dark" />
        </Link>

        <div className="rounded-3xl p-8 md:p-12" style={{ background: "linear-gradient(135deg, var(--glass-bg) 0%, var(--glass-bg-end) 100%)", border: "1px solid var(--glass-border)", boxShadow: "var(--card-shadow)" }}>
          <h1 className="text-3xl font-bold text-foreground mb-2">Terms of Use</h1>
          <p className="text-muted text-sm mb-1">UpStar Five Ltd</p>
          <p className="text-muted text-sm mb-10">Effective Date: June 07, 2026</p>

          <p className="text-sm leading-relaxed mb-8" style={{ color: "var(--text-secondary)" }}>
            Welcome to UpStar! This document outlines our Terms of Use, Privacy Policy, and pricing and subscription details. UpStar Five Ltd (referred to as “UpStar,” “we,” or “us”) provides AI-powered services for hotels worldwide (For URI, UpStar is authorized to publish responses on the Customer’s behalf under the Customer’s platform accounts.) By using our services, you (“Customer” or “you”) agree to the following terms and policies. Please read them carefully.
          </p>

          <div className="space-y-8 text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using UpStar’s services, you agree to these Terms of Use and all policies referenced herein. If you disagree, you must not use our services. If you are using UpStar on behalf of a company (such as a hotel), you represent that you have the authority to bind that company to these terms. These Terms of Use, the Privacy Policy, and the Pricing terms below form a binding agreement between UpStar Five Ltd (Company No. 517163234) and you.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">2. Our Services</h2>
              <p>UpStar provides two subscription-based services for hospitality businesses:</p>
              <p><strong className="text-foreground">2.1. UpStar Replier:</strong> An AI chatbot service delivered via WhatsApp that helps hoteliers draft responses to public guest reviews in real time. This service uses OpenAI-powered language generation to suggest polite, context-aware replies that hotel staff can review and post to guest review platforms. The plan includes up to 300 AI-generated replies per hotel per billing month; additional replies are billed at USD 0.50 each.</p>
              <p><strong className="text-foreground">2.2. UpStar Rating Improvement (“URI”):</strong> A subscription service focused on measurably improving the hotel&apos;s Booking.com rating under the SLA Exhibits below. URI includes strategic auto-posting: UpStar is authorized to draft and publish responses on the Customer&apos;s behalf on Booking.com, Google, TripAdvisor, and Expedia. UpStar may decide, per review, whether to auto-post using AI or route to human review. URI also provides analytics, prioritized fixes with quantified rating impact, competitor deep dives, live alerts, and growth insights. For URI, there is no per-message cap; UpStar is responsible for replying to every in-scope review on the four platforms. Platform approval/moderation queues are outside UpStar&apos;s control; URI&apos;s 24-hour response SLA measures submission time, not publication time. These services (collectively, the “Services”) are provided by UpStar Five Ltd, headquartered in Israel, and offered to customers globally. We reserve the right to add or modify service features at any time. All use of the Services is subject to these Terms.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">3. Eligibility</h2>
              <p>Our Services are intended for business use by hotels and hospitality professionals. You must be at least 18 years old to use UpStar. By using the Services, you confirm that you are at least 18 years old and an employee or authorized representative of a hotel or related business. You agree to use UpStar only for lawful business purposes and not for personal or household use.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">4. Account Setup and Communication</h2>
              <p>To use UpStar, you may need to provide certain information and set up an account or service access with us. For UpStar Replier and URI, you will interact with our AI via WhatsApp; therefore, you must have a valid WhatsApp account and authorize communication with our WhatsApp business number. You agree to provide accurate contact information (such as your name, hotel name, and phone number) and keep it updated. You are responsible for maintaining the confidentiality of any authentication credentials and for all activities under your account or through your authorized WhatsApp number. Please notify us at <a href="mailto:hotels@rating-iq.com" className="transition-colors" style={{ color: "var(--gold)" }}>hotels@upstar5.com</a> if you suspect unauthorized use of your account or the Services. For URI, Customer will provide timely delegated access/valid credentials to in-scope review platforms and authorize UpStar to post on Customer&apos;s behalf.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">5. Subscription Plans and Fees</h2>
              <p>We offer our Services on a subscription basis with two main plans (see the Pricing &amp; Subscription section below for detailed pricing):</p>
              <p><strong className="text-foreground">5.1. UpStar Replier Plan:</strong> Subscribe monthly or annually (up-front) per hotel.</p>
              <p><strong className="text-foreground">5.2. URI Plan:</strong> Annual service with chain discounts; special billing rules apply (see Pricing/Exhibits F–G).. You agree to pay the applicable fees for your chosen plan and term by subscribing to it. All payments are stated in U.S. Dollars (USD) unless otherwise agreed. Subscription fees are invoiced per hotel and cover use of the Services for that hotel. If you add additional hotel properties, each is subject to its subscription fee. You are responsible for any taxes or duties applicable to the fees (except taxes on our income). We will not charge VAT for international customers unless required to do so by law. However, Israeli customers may be subject to VAT as per Israeli law.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">6. Free Trial and Evaluation Use</h2>
              <p>We offer a limited free trial so you can evaluate our Services:</p>
              <p><strong className="text-foreground">6.1. UpStar Replier Trial:</strong> New customers receive the first 10 message responses free of charge. This allows you to try the AI bot (via WhatsApp) to draft up to 10 guest review replies before subscribing. After the 10 complimentary messages, continued use of UpStar Replier requires a paid subscription. Hotels that later upgrade to URI still benefit from this per-user, per-hotel allowance. Each registered user (by unique WhatsApp number) at a property receives 10 complimentary messages for that property. Trial is available to new customers (or as otherwise agreed with us) and are intended solely for evaluation. During the trial, these Terms of Use remain in effect. We reserve the right to end or withdraw a free trial if we suspect any form of abuse. After a trial, if you do not subscribe, your access to the Service will be disabled, and any data collected during the trial will be retained or deleted in accordance with our Privacy Policy and data retention rules. From time to time, we may offer a client-specific pilot or service-level agreement, governed by a separate signed addendum for the named property. If such an addendum is signed, it controls for that property.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">7. Payment Terms</h2>
              <p>UpStar will issue subscription fee invoices, which must be paid via wire transfer to our Bank Hapoalim account (details will be provided on the invoice). For URI, 25% is due at signature (covers Q1), and 75% is due after Q1 only if Q1 improves by ≥ +0.10 vs Baseline (see Exhibits F–G). Payment is due within 30 days from the invoice date (net 30 terms). You are responsible for any bank transfer fees on your side. We currently do not accept credit cards or other payment methods unless explicitly agreed upon. If payment is not received by the due date, we reserve the right to suspend or terminate your access to the Services, if we have given you notice. We may also charge late-payment interest at the standard rate permitted by law for overdue invoices, accruing from the due date until payment is made in full. (Interest will not exceed any rate limit under applicable law.) All fees paid are non-refundable. As is standard in the SaaS industry, UpStar maintains a no- refunds policy for subscription fees (no pro-rated refunds for unused portions of a billing period). This means that once a payment is made for a month or year, the payment is final and will not be refunded if you decide to cancel or stop using the Service during that period, except where a refund is required by law. Please review any trial offerings (as described above) before committing to a paid plan.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">8. Term, Renewal, and Cancellation</h2>
              <p>Term and Auto-Renewal: Your subscription term will commence on the subscription start date and continue for the selected period (monthly or annual). Monthly plans continue month-to-month until cancelled. Yearly plans are valid for 12 months and will automatically renew for successive one-year terms unless cancelled with advance notice, as described below. We will provide a reminder or invoice before renewal. You must notify us if you intend not to renew. Cancellation by Customer: You may cancel your subscription as follows:</p>
              <p><strong className="text-foreground">8.1. Monthly Subscription (UpStar Replier only):</strong> You may cancel a monthly plan by giving UpStar at least 30 days’ notice (via email to <a href="mailto:hotels@rating-iq.com" className="transition-colors" style={{ color: "var(--gold)" }}>hotels@upstar5.com</a>). Your subscription will remain active until the end of the next billing cycle, following a 30-day notice period. For example, if you pay monthly on the 1st of each month and you give notice on June 15, your service will terminate on July 31. No further billing will occur after the effective cancellation date.</p>
              <p><strong className="text-foreground">8.2. Annual Subscription (UpStar Replier or URI):</strong> Annual plans are paid in one lump- sum invoice for the full 12-month term. They are generally non-cancellable during that term. Initial term is 12 months per property and auto-renews annually unless either party gives 30 days’ prior notice. Billing for URI follows Exhibits F–G (25% at signature; 75% after Q1 only if Q1 ≥ +0.10 vs Baseline). Q1 Exit Right: If Q1 delta ≤ 0.00, the Customer may terminate the affected property effective at the end of Q1 and receive 50% of Q1 fees (see Exhibit E).</p>
              <p><strong className="text-foreground">8.3.</strong> All cancellation notices should be sent in writing to <a href="mailto:hotels@rating-iq.com" className="transition-colors" style={{ color: "var(--gold)" }}>hotels@upstar5.com</a>. Upon cancellation or expiration of your subscription, your access to the Services will end as of the termination date. We recommend exporting or saving any necessary data or reports before termination. UpStar will retain customer data for 24 months after termination (see Privacy Policy) in case you reactivate or need data restored. After this period, we will delete personal data in accordance with our data retention policy. Termination by UpStar: We reserve the right to suspend or terminate your access to the Services for cause if you materially breach these Terms (including non-payment) and do not cure the breach within 15 days of our notice. In cases of severe violation (for example, wilful misuse of the system for unlawful purposes), we may suspend or terminate immediately. If we terminate for cause due to your breach, you will not be entitled to any refund of fees paid. We may also terminate the Services or your subscription at our discretion, providing you with 60 days’ notice. If we do so (excluding cases of your breach), we will refund any prepaid fees on a pro rata basis for the remaining term.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">9. Acceptable Use Policy</h2>
              <p>You agree to use UpStar’s Services responsibly and in compliance with all applicable laws and regulations. You must not misuse the Services. You agree that you will NOT:</p>
              <p><strong className="text-foreground">9.1.</strong> Use the Services to generate or transmit any content that is illegal, harmful, threatening, abusive, harassing, defamatory, libelous, vulgar, obscene, pornographic, hateful, or otherwise objectionable. This includes content that constitutes hate speech, incitement of violence, or discrimination based on race, ethnicity, national origin, religion, gender, sexual orientation, disability, or any other characteristic. We prohibit the use of UpStar to create or disseminate any such content.</p>
              <p><strong className="text-foreground">9.2.</strong> Use the Services in any manner that violates the rights of others or the law. For example, you will not use UpStar to infringe or misappropriate anyone’s intellectual property rights or privacy rights or violate any laws (including data protection laws, export control, or consumer protection laws).</p>
              <p><strong className="text-foreground">9.3.</strong> Input or provide to UpStar any personal data of individuals (such as hotel guests) unless you have a lawful basis to do so. Suppose you provide UpStar with third parties&apos; data (e.g., a guest’s name or reservation number). In that case, you represent and warrant that you have obtained all necessary consents or have another valid legal basis to share the data with us to use the Services.</p>
              <p><strong className="text-foreground">9.4. Use the Services to send unsolicited messages or spam to anyone. (Note:</strong> UpStar Replier is meant to respond to guest reviews on public platforms or directly to feedback you’ve received, not to initiate contact with guests who haven’t contacted you.)</p>
              <p><strong className="text-foreground">9.5.</strong> Do not solicit, fabricate, gate, suppress, or otherwise manipulate reviews in ways that violate platform policies; do not offer incentives for positive reviews or selectively invite only satisfied guests.</p>
              <p><strong className="text-foreground">9.6.</strong> Attempt to leverage the Services for any purpose other than the hotel customer- engagement and analytics purposes for which they are intended. You will not use the Services to process or store sensitive personal information unrelated to guest reviews and hotel operations (for example, do not input credit card numbers, national ID numbers, health or medical information, or any other highly sensitive data into the system).</p>
              <p><strong className="text-foreground">9.7.</strong> Interfere with or disrupt the integrity or performance of the Services. This means you will not attempt to hack, overload, or attack our systems or those of our sub-processors, introduce viruses or malware, or try to bypass any security measures.</p>
              <p><strong className="text-foreground">9.8.</strong> Reverse engineer, decompile, or otherwise attempt to discover the source code, algorithms, or trade secrets underlying the Services (including the AI models and prompts). You also agree not to use automated means (such as bots or scrapers) to extract data or content from our Services beyond what is intended.</p>
              <p><strong className="text-foreground">9.9.</strong> Do not misrepresent your identity or affiliation when using the Services. For example, when using UpStar Replier to respond to a guest, you should not pretend to be someone you are not.</p>
              <p><strong className="text-foreground">9.10.</strong> Use the Services in a manner that violates WhatsApp’s terms of service or policies, or OpenAI’s acceptable use policies. (Our Service relies on WhatsApp and OpenAI’s technology; for instance, OpenAI’s terms prohibit certain content like illegal activities, child exploitation, etc. You agree not to use UpStar to attempt to generate content that would violate those underlying provider policies.)</p>
              <p><strong className="text-foreground">9.11. Auto-Post Authorization (URI):</strong> By subscribing to URI, Customer authorizes UpStar to generate and publish review responses under Customer&apos;s platform accounts for Booking.com, Google, TripAdvisor, and Expedia. Customer remains the publisher of record. The customer may disable auto-post at any time via written notice or via a supported interface (including a kill-switch/stop command). UpStar maintains immutable logs and will, upon request, retract or edit specific responses within 24 hours (commercially reasonable efforts). UpStar is not responsible for platform moderation queues, approval delays, or rejections beyond its control (while using commercially reasonable efforts to minimize rejections). If you violate the above acceptable use rules or any other provision of these Terms, UpStar may suspend your account or terminate service, as noted in the termination section. We may also filter or remove any content that we determine (in our reasonable discretion) violates the above standards. You are responsible for any consequences (legal or otherwise) arising from content you or your employees generate or distribute using UpStar.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">10. Intellectual Property Rights</h2>
              <p><strong className="text-foreground">10.1. UpStar’s IP:</strong> All rights, title, and interest in and to the UpStar Services, including our software, algorithms, AI prompt designs, models, websites, dashboards, databases, documentation, trademarks (like the “UpStar” name and logo), and any other proprietary technology or content provided by us, are owned by UpStar Five Ltd or our licensors. The Terms of Use do not transfer intellectual property rights to you except for the limited license to use the Services as described. You agree not to copy, modify, distribute, sell, or lease any part of our Services or included software, nor reverse engineer or attempt to extract the software&apos;s source code, except to the extent laws prohibit such restrictions.</p>
              <p><strong className="text-foreground">10.2. Customer’s IP and Data:</strong> You retain ownership of all content and data you provide to UpStar, including the text of guest reviews (originating from your guests or public sources) and any information you submit (e.g., reservation numbers, internal notes, or other data you input). UpStar does not claim ownership of your or your hotel’s data. You grant UpStar a license to use, process, and transmit your data solely for the purpose of providing and improving the Services. This includes, for example, feeding a guest review you send us into our AI system to generate a reply, analysing your data to produce reports, and storing it on our sub-processor platforms (WhatsApp, OpenAI, Landbot, OneDrive) as needed. This license is worldwide, royalty-free, non-exclusive, and limited to the term of your use of the Services, as well as a reasonable period thereafter for post-termination data handling.</p>
              <p><strong className="text-foreground">10.3.</strong> AI Outputs:</p>
              <p><strong className="text-foreground">10.3.1.</strong> (a) UpStar Replier (draft-only). The responses generated by the UpStar AI when you use Replier (“Outputs”) are drafts provided for your use. As between you and UpStar, and to the extent protectable under applicable law, UpStar assigns to you any rights UpStar may have in the content of the Outputs (excluding UpStar&apos;s underlying IP, such as prompts, models, templates, and tooling). Where assignment is not effective by law, UpStar grants you a perpetual, worldwide, royalty-free licence to use, edit, and publish the Outputs for the subscribed hotel. Outputs may incorporate or be derived from third-party material (e.g., a guest&apos;s review text or platform snippets); you are responsible for ensuring your publication and use of any Output complies with law and platform rules. You must review and approve each Output before publishing it as your hotel&apos;s response. Replier does not auto-post, and UpStar is not the publisher of Replier Outputs.</p>
              <p><strong className="text-foreground">10.3.2.</strong> (b) UpStar Rating Improvement (URI) (auto-post). For URI, UpStar is authorized to generate and publish responses under your platform accounts (Booking.com, Google, TripAdvisor, Expedia). You acknowledge and agree that you are the publisher of record for all auto-posted content. Upon your request, UpStar will either retract or edit a specific response within 24 hours (to the extent commercially reasonable). Ownership of URI Outputs follows the same rule as in 10.3.1(a): you receive assignment (or, where not possible, a perpetual licence) to the content of the Outputs, excluding UpStar&apos;s underlying IP. URI Outputs may include or reference third-party/platform material and remain subject to those platforms&apos; terms; platform moderation, rejection, or publication delays are outside UpStar&apos;s control. You remain responsible for compliance with review- platform policies (including no solicitation/fabrication/gating/suppression of reviews).</p>
              <p><strong className="text-foreground">10.3.3. Restrictions (both services):</strong> You may use Outputs only for the subscribed hotel property; no resale, re-licensing, or use to train competing services; no attempt to extract, copy, or reverse-engineer UpStar&apos;s prompts or internal methods.</p>
              <p><strong className="text-foreground">10.4. Anonymized Data Use:</strong> UpStar is permitted to retain and use aggregated or anonymized data derived from your use of the Services for analytics, product improvement, and benchmarking. For example, we might compile statistics on common guest complaints or overall changes in review scores across our clients. Any such data will be stripped of personal identifiers and not linked to your hotel’s identity in any public reporting. We will not sell or disclose any personal data or customer-specific data to third parties except as described in our Privacy Policy. This anonymized usage of data helps us improve our AI models and provide industry insights without compromising privacy.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">11. Privacy and Data Protection</h2>
              <p><strong className="text-foreground">11.1.</strong> Your privacy is of the utmost importance to us. Our Privacy Policy (see below) explains what data we collect and how we process and protect it. By using the Services, you also agree to the terms of the Privacy Policy. In summary, we comply with applicable data protection laws, including the EU General Data Protection Regulation (GDPR) and Israeli Limitation of Liability.</p>
              <p><strong className="text-foreground">11.2.</strong> We comply with the EU General Data Protection Regulation and Israeli privacy law to safeguard personal data. Key points: We only collect data necessary to provide the Services. We obtain appropriate consent before processing personal data. We use reputable sub-processors to host and process data. You have rights regarding your data.</p>
              <p><strong className="text-foreground">11.3.</strong> UpStar Five Ltd is an Israeli company, and the personal data we handle may be transferred to and processed in Israel or other countries where our service providers operate. Israel is recognized as providing adequate data protection under EU law, and for other international transfers, we implement standard safeguards (such as Standard Contractual Clauses, where required). We have appointed a Data Protection Officer (see our Privacy Policy for contact details) and are in the process of appointing an EU representative to ensure compliance with GDPR Article 27. If you are a hotel using UpStar, you may be the “data controller” of your guests’ data, and UpStar acts as a “data processor” on your behalf for that data. We will only process such personal data in accordance with your instructions and our agreement, which includes these Terms, our Privacy Policy, and a Data Processing Addendum (if applicable).</p>
              <p><strong className="text-foreground">11.4.</strong> Please review the Privacy Policy below for complete details. If you have questions about privacy or need a separate Data Processing Agreement (DPA) for your company’s compliance, contact us at <a href="mailto:hotels@rating-iq.com" className="transition-colors" style={{ color: "var(--gold)" }}>hotels@upstar5.com</a> (Attn: Data Protection Officer).</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">12. Support and Service Level Agreement</h2>
              <p>We are committed to providing reliable service and support to our customers:</p>
              <p><strong className="text-foreground">12.1. Support Channels:</strong> UpStar offers 24/7 customer support via WhatsApp and email. You can reach our support team at any time by messaging our dedicated WhatsApp support line +972-542-533-296 or emailing <a href="mailto:hotels@rating-iq.com" className="transition-colors" style={{ color: "var(--gold)" }}>hotels@upstar5.com</a>. We strive to be available around the clock, as we understand that hoteliers operate 24/7.</p>
              <p><strong className="text-foreground">12.2. Response Time:</strong> We aim to respond to all support inquiries within 24 hours. In practice, most queries are addressed within a few minutes. Simple issues may be resolved immediately via the WhatsApp chat. More complex questions or technical problems may take longer to resolve, but we will acknowledge your request and keep you updated on our progress.</p>
              <p><strong className="text-foreground">12.3. URI Consultations:</strong> If you are a URI customer, UpStar may provide human consultation on a best efforts basis. These consultation services are provided on a best- effort basis. This means we will do our utmost to schedule calls or provide detailed feedback on time, but we do not guarantee an immediate turnaround for in-depth consulting requests. Typically, we can arrange a consultation or deliver a custom analysis within a few business days of your request. URI Service Levels (monitoring, response time, platforms, languages, exclusions) are set out in Exhibits B–C. The response SLA measures UpStar’s submission time; platform moderation/approval delays are excluded.</p>
              <p><strong className="text-foreground">12.4. Service Availability:</strong> Our AI chatbot services rely on third-party platforms (WhatsApp, OpenAI, etc.). We cannot guarantee 100% uptime, but our goal is to maintain high availability. If there are planned downtimes or maintenance windows for our systems, we will inform you in advance. Suppose an unplanned outage occurs (e.g., a disruption to the WhatsApp service or downtime of the OpenAI API). In that case, we will communicate status updates and work with our providers to restore service as quickly as possible. Please note that such outages are outside our direct control; however, we will use commercially reasonable efforts to mitigate any resulting disruption.</p>
              <p><strong className="text-foreground">12.5. No Guaranteed Outcome:</strong> While our Service is designed to help improve your efficiency and guest satisfaction, we cannot guarantee specific outcomes (such as a particular increase in your review scores). The success of the tool also depends on your usage and other factors. The URI plan’s early termination option for lack of a 0.1-point rating increase is provided as a courtesy (see Section 8), but this is not a guarantee that such an increase will occur, nor a warranty of performance. You have the option to exit the contract if you are unsatisfied with the results under these conditions.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">13. Disclaimer of Warranties</h2>
              <p>Use at Your Own Risk: UpStar’s Services are provided “as is” and “as available.” To the maximum extent permitted by law, we disclaim all warranties of any kind, whether express, implied, or statutory, including any warranties of merchantability, fitness for a particular purpose, title, non-infringement, and any warranties arising from course of dealing or usage of trade. While we strive for accuracy and helpfulness, we do not guarantee that the AI-generated responses or analytics will be error-free, accurate, or meet all your expectations. AI is probabilistic and can sometimes produce incorrect or inappropriate suggestions. It is the user’s responsibility to review AI-generated content before using it (for example, before posting a response to a guest). UpStar is an aid to your operations, but it cannot replace human judgment. We do not warrant that using the Services will improve your guest ratings or revenue (though we certainly aim to help in that regard). Aside from the limited cancellation right for URI mentioned above, no remedies or guarantees are given for not achieving particular results. Furthermore, we do not warrant that the Services will be uninterrupted, timely, secure, or error-free. While we take data security seriously, we do not guarantee that the Services are immune to every possible security breach or virus. You understand that using the Services involves transmitting data over networks that we do not control (such as WhatsApp and the internet), and that there is an inherent risk associated with any such transmission. Some jurisdictions do not allow the exclusion of certain warranties, so some of the above disclaimers may not apply to you. In such cases, any mandatory warranties are limited in duration to 30 days from the start of service (unless the law requires a longer duration) and are limited to the minimum scope permitted by law.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">14. Limitation of Liability</h2>
              <p>To the fullest extent permitted by applicable law, UpStar and its directors, officers, employees, and agents shall not be liable to you or any third party for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, goodwill, or other intangible losses, arising out of or related to your use of (or inability to use) the Services, even if we have been advised of the possibility of such damages. This limitation applies to all causes of action, whether in contract, tort (including negligence), strict liability, or any other legal theory. In no event will UpStar’s total cumulative liability for all claims arising from or related to the Services and these Terms exceed the total amount of fees you have paid to UpStar in the six months immediately preceding the event giving rise to the liability. If you have not paid any costs (for example, if a claim arises during a free trial), UpStar&apos;s total liability shall not exceed US$100. These limitations of liability reflect an agreed allocation of risk between you and us; without them, the pricing of the service would be different. You acknowledge that this limitation is reasonable. Some jurisdictions do not allow the exclusion or limitation of certain liabilities, so the above limitation may not fully apply to you. In such cases, our liability is limited to the smallest amount or narrowest scope permitted by applicable law. For URI, the sole and exclusive remedy for failing the Exhibit-E Target is the refund described in Exhibit E. Except for UpStar’s wilful misconduct, Customer is the publisher of record for URI auto-posted content and shall indemnify UpStar for claims arising therefrom.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">15. Indemnification</h2>
              <p>You agree to indemnify, defend, and hold harmless UpStar Five Ltd and our affiliates, and our respective officers, directors, employees, and agents, from and against all claims, liabilities, damages, losses, and expenses (including reasonable attorneys’ fees and costs) that arise out of or relate to: (a) your use of the Services (including any content you or your staff submit through the Services); (b) your violation of these Terms of Use or any policy incorporated by reference; (c) your violation of any law or regulation (including data protection laws or consumer laws) in connection with your use of the Services; or (d) any claim that content you provided (such as a response to a guest or data you uploaded) infringes or violates the rights of a third party, including any claim arising from Customer’s failure to meet Exhibit D obligations or from fraud/manipulation of reviews (e.g., incenting, gating, fabricating, or suppressing reviews contrary to platform rules).. This indemnity includes, for example, claims by guests or other third parties arising from your hotel&apos;s use of the AI- generated responses (e.g., if a guest claims a response was inappropriate or violated their rights) or claims by individuals whose personal data you provided to us without proper authority. We reserve the right to assume the exclusive defence and control of any matter otherwise subject to indemnification by you (at your expense), and you agree to cooperate with our defence of such claim. You will not settle a matter that imposes any obligation on UpStar without our prior written consent.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">16. Changes to Service or Terms</h2>
              <p>UpStar is an evolving service, and we may update the Services or these Terms over time:</p>
              <p><strong className="text-foreground">16.1. Changes to Services:</strong> We reserve the right to modify or discontinue (temporarily or permanently) any part of the Services at any time. For example, we may add new features, update the AI models, or discontinue a feature that has become outdated. We will endeavour to notify you (for instance, via email or in-service notification) of any material changes to the Services or features you are actively using. If any change will significantly reduce functionality or value, we will provide reasonable advance notice when feasible.</p>
              <p><strong className="text-foreground">16.2. Changes to Terms:</strong> We reserve the right to update these Terms of Use from time to time to reflect changes in the law or our Services. When we make material changes, we will notify customers by email or through a prominent notice on our Service (for example, a WhatsApp message or dashboard alert) before the change taking effect. The notice will designate a reasonable advance notice period and the “effective date” of the updated Terms. If you continue to use the Services after the new Terms take effect, you will be deemed to have accepted the changes. If you do not agree to the revised Terms, you must stop using the Services before the changes take effect, and you may terminate your subscription as provided in Section 8. The effective date at the top of this document indicates when these Terms (or any updated version) take effect. We encourage you to check back periodically for updates. Historical versions can be provided upon request.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">17. Governing Law and Jurisdiction</h2>
              <p>These Terms of Use (and any disputes arising out of or related to the Services or this agreement) shall be governed by and construed by the laws of the State of Israel, without regard to its conflict of law principles. You and UpStar agree that all disputes shall be subject to the exclusive jurisdiction of the courts located in Tel Aviv, Israel. Both parties consent to the personal jurisdiction of these courts and waive any objections on the grounds of venue or inconvenient forum, to the extent permitted by law. Suppose you are accessing the Services from outside Israel. In that case, you are responsible for complying with local laws to the extent they apply. Use of the Services is not authorized in any jurisdiction that does not give effect to all provisions of these terms, including, without limitation, this paragraph.</p>
            </section>

            <section>
              <h2 className="text-foreground font-semibold text-lg mb-3">18. Miscellaneous</h2>
              <p><strong className="text-foreground">18.1. Company Details:</strong> UpStar Five Ltd is a company registered in Israel (Company No. 517163234), with its principal business address at HaBrosh St 9, Beit Nekofa, Jerusalem district, Israel.</p>
              <p><strong className="text-foreground">18.2. Communication and Notices:</strong> The primary email contact for UpStar is <a href="mailto:hotels@rating-iq.com" className="transition-colors" style={{ color: "var(--gold)" }}>hotels@upstar5.com</a>. For any questions regarding these Terms, your subscription, or to send formal notices, please email us or send postal mail to our business address. We may send you notices via email to the address associated with your account, via WhatsApp, or via other contact methods you provide. It is your responsibility to keep your contact information up to date. Notices will be deemed received on the day sent (for electronic communications) or five business days after posting (for physical mail).</p>
              <p><strong className="text-foreground">18.3. Entire Agreement:</strong> These Terms of Use, together with the Privacy Policy and Pricing terms herein and any order form or service agreement and any order form or service agreement including any pilot SLA or statement of work you have executed with us you have executed with us, constitute the entire agreement between you and UpStar regarding the Services and supersede any prior agreements or understandings (whether written or oral) relating to the same subject matter. In case of conflict, an individually negotiated and signed contract (if applicable) will prevail over these online Terms, and these Terms will prevail over the Privacy Policy for any inconsistency concerning legal use of the Service (however, nothing in these Terms limits our obligations to protect personal data as stated in the Privacy Policy).</p>
              <p><strong className="text-foreground">18.4. Assignment:</strong> You may not assign or transfer any of your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations to an affiliate or in connection with a merger, acquisition, or sale of assets, or by operation of law or otherwise. These Terms will bind and benefit any permitted successors or assigns.</p>
              <p><strong className="text-foreground">18.5. No Waiver:</strong> If UpStar fails to enforce any provision of these Terms, it will not be considered a waiver of our rights. Any waiver of any provision by us on one occasion shall not constitute a waiver of that provision on any other occasion.</p>
              <p><strong className="text-foreground">18.6. Severability:</strong> If any provision of these Terms is held to be invalid or unenforceable by a competent court, that provision will be enforced to the maximum extent permissible, and the remaining provisions of these Terms will remain in full force and effect.</p>
              <p><strong className="text-foreground">18.7. Relationship:</strong> Nothing in these Terms creates a partnership, joint venture, agency, or employment relationship between you and UpStar. You and I are independent contracting parties.</p>
              <p><strong className="text-foreground">18.8. Third-Party Services:</strong> Our Services rely on third-party platforms (e.g., WhatsApp, provided by Meta; OpenAI’s services; Landbot.io; Microsoft OneDrive). Your use of those services through UpStar is also subject to their terms of service. For example, using UpStar’s WhatsApp integration also binds you to WhatsApp’s terms and policies. We are not liable for the acts or omissions of these third-party services. However, suppose any such third-party service’s terms require us to impose additional restrictions on your use of UpStar. In that case, we will communicate those in our Acceptable Use Policy or directly to you.</p>
              <p><strong className="text-foreground">18.9. Force Majeure:</strong> UpStar will not be liable for any delay or failure in performance of the Services caused by circumstances beyond our reasonable control, such as acts of God, war, terrorism, civil disturbance, strikes or labour disputes, internet or utility failures, supply shortages, or actions of third-party service providers or governments. We will endeavour to mitigate the impact and resume service as soon as feasible in such events.</p>
              <p><strong className="text-foreground">18.10.</strong> Confidentiality. Each party will keep the other party&apos;s non-public information confidential and will use it only to perform its obligations under these Terms. The receiving party will protect the information with reasonable care. It may disclose it only to its personnel and providers who need to know it and who are bound by confidentiality obligations. These duties do not apply to information that is public without breach, already known, independently developed, or rightfully received from a third party. Upon request or termination, the receiving party will return or delete the other party&apos;s confidential information, except for archival copies kept for legal compliance. If you have any questions or require clarification on these Terms of Use, please contact us at <a href="mailto:hotels@rating-iq.com" className="transition-colors" style={{ color: "var(--gold)" }}>hotels@upstar5.com</a>. We value our partnership with our hotel clients and aim to be transparent and fair in all our dealings.</p>
            </section>

          </div>
        </div>

        <div className="text-center mt-8">
          <Link href="/privacy" className="text-sm transition-colors" style={{ color: "var(--gold)" }}>
            View Privacy Policy &rarr;
          </Link>
        </div>
      </div>
    </div>
  );
}
